### ISSUE TITLE
mysqli_error given 0 args, but 1 expected

### ISSUE THREAD

**Issue by VinWare** [lmoroz/bWAPP#1]
When SQL Injection is performed on GET/Search, if an incorrect query is sent, the server says that one argument is needed for mysqli_error. Although I am not sure if this is one of the bugs expressly included, it seems not, because the error is only visible on the server end; the client simply has "Error:" printed out.

Can be checked by URL
http://localhost:4000/sqli_1.php?title=%27or1%3D1%3B--&action=search
![BWAPP mysqli error](https://user-images.githubusercontent.com/28603906/66066595-74792780-e567-11e9-8c47-5a9730a5bd5d.png)

**Comment by watto33** [comment]
I have solved this issue and made a pull request to this repo.

Meanwhile, you can get the code at https://github.com/watto33/bWAPP
